server:
  port: 8080

spring:
  application:
    name: api-service
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5432}/${POSTGRES_DB_NAME:jobs}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    mapper:
      accept-case-insensitive-enums: true

  kafka:
    bootstrap-servers:
      - localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE