server:
  port: 8080

spring:
  application:
    name: api-service
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5432}/${POSTGRES_DB_NAME:jobs}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver